/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.net.ConnectException;
import java.sql.*;
import javax.swing.JOptionPane;
import static jframe.DBConnection.con;

/**
 *
 * @author Hello
 */
public class SingupPage extends javax.swing.JFrame {

    /**
     * Creates new form sup
     */
    public SingupPage() {
        initComponents();
    }
      
       public void insertSignupDetails(){
           
       // DBConnection db=new DBConnection();
        String name = txt_username.getText();
        String password = txt_password.getText();
        String email = txt_email.getText();
        String number = txt_number.getText();
        
           try {
               Connection con = DBConnection.getConnection();
               String sql = "insert into users(name,password,email,number) values (?,?,?,?)";
               PreparedStatement pst =con.prepareStatement(sql);
               
               pst.setString(1,name);
               pst.setString(2, password);
               pst.setString(3, email);
               pst.setString(4, number);
               
               int updatedRowCount = pst.executeUpdate();
               if(updatedRowCount >0 )
               {
                   JOptionPane.showMessageDialog(this, "Recorded Successful");
                   LoginPage page = new LoginPage();
                   page.setVisible(true);
                   dispose(); 
                   
                           
                       
               }
               else
               {
                   JOptionPane.showMessageDialog(this, "Not Recorded");
               }
           } catch (Exception e) {
               e.printStackTrace();
           }
    
       }       
       // validation
       
        public boolean vaildateSingup(){
        
        String name = txt_username.getText();
        String password = txt_password.getText();
        String email = txt_email.getText();
        String number = txt_number.getText();
        
        if(name.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter username");
            return false;
        }
        if(password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "please enter password");
            return false;
        }
        if(email.equals("") || !email.matches("^.+@.+\\..+$"))
        {
            JOptionPane.showMessageDialog(this, "please enter valid email");
            return false;
        }
        if(number.equals(""))
        {
            JOptionPane.showMessageDialog(this, "enter number");
            return false; 
        } 
        return true;
    }
                
        // check duplication
        
         public  boolean checkDuplicateUser() {
         String name = txt_username.getText();
         boolean isExits=false;
         try { 
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root",""); 
                
                PreparedStatement pst = con.prepareStatement("select * from users where name = ?");
                
                pst.setString(1, name);                
                ResultSet rs = pst.executeQuery();
                
                if(rs.next())
                {
                    isExits = true;
                }
                else
                {
                    isExits = false;
                    
                }                
        } catch (Exception e) {
            e.printStackTrace();
        }        
         return isExits;        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new app.bolivia.swing.JCTextField();
        txt_number = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new rojerusan.RSMaterialButtonCircle();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(75, 185, 62));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 185, 62));
        jLabel1.setText("Green University of Bangladesh");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Project oop\\gub_banner-2.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 560, 550));

        jLabel6.setBackground(new java.awt.Color(75, 185, 62));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 185, 62));
        jLabel6.setText("Welcome to Smart Library Management System");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 560, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 770));

        jPanel3.setBackground(new java.awt.Color(75, 185, 62));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Project oop\\username icon.png")); // NOI18N
        jLabel2.setText("Username");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(496, 10, 20, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Create New Account");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        txt_username.setPlaceholder("enter username...");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel3.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Project oop\\lock-icon.png")); // NOI18N
        jLabel7.setText("Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 30));

        txt_password.setPlaceholder("enter pasword...");
        jPanel3.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Project oop\\email_icon_5065641.png")); // NOI18N
        jLabel8.setText("Email");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, 30));

        txt_email.setPlaceholder("enter email...");
        jPanel3.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        txt_number.setPlaceholder("enter number...");
        jPanel3.add(txt_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("E:\\Project oop\\telephone icon.png")); // NOI18N
        jLabel9.setText("Mobile Number");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 30));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(0, 204, 204));
        rSMaterialButtonCircle1.setText("Login");
        jPanel3.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, 170, 50));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(255, 51, 102));
        rSMaterialButtonCircle2.setText("Singup");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 170, 50));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setText("Singup Page");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 540, 770));

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        
        // singin button
        if(vaildateSingup() == true){
            if (checkDuplicateUser() == false) {
                insertSignupDetails();                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "username already exist");
            }       
        }
        
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        // for 'x'
        System.exit(0);
        
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        // TODO add your handling code here:
    
        // foucas lost even
            
        
        
//        if(vaildateSingup() == true){
//            
//        }

        if(checkDuplicateUser() == true ){
            JOptionPane.showMessageDialog(this, "username already exist");
        }
        
       
    }//GEN-LAST:event_txt_usernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_number;
    private app.bolivia.swing.JCTextField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
